on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: git.codaealab.com/Codaea/guesscity

jobs:
  build:
    runs-on: docker

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.codaealab.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and tag Docker image
        run: |
          docker build -t Codaea/guesscity:latest .

      - name: Push Docker image
        run: |
          docker push your-username/your-repo:latest
