on: 
  push:
    branches:
      - main

env:
  IMAGE_NAME: git.codaealab.com/Codaea/guesscity

jobs:
  build-deploy:
    runs-on: docker

    steps:
      - uses: actions/checkout@v4
      
    - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.codaealab.com
          username: ${{ github.actor }}
          password: ${{ secrets.password }}

    - name: Set Docker tag
        id: date
        run: echo "DATE_STAMP=$(date +%s)" > "$GITHUB_ENV"

    - name: Build and push Docker images
        uses: iloveitaly/github-action-nixpacks@main
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:custom-${{ env.DATE_STAMP }}
            ${{ env.IMAGE_NAME }}:latest